# Generated by Django 3.1.5 on 2021-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
