# Generated by Django 3.1.6 on 2021-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0002_room_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="location",
        ),
    ]
