# Generated by Django 3.1.6 on 2021-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0003_remove_room_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="block_whole_room",
            field=models.BooleanField(default=False),
        ),
    ]
